# Generated by Django 3.2 on 2021-04-28 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='deviceid',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
