# Generated by Django 3.2 on 2021-04-29 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_alter_device_deviceid'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='data',
            field=models.JSONField(default={'test': 'test'}),
        ),
    ]
