# Generated by Django 3.2 on 2021-04-29 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_location_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='data',
            field=models.JSONField(default=dict),
        ),
    ]
