# Generated by Django 3.2 on 2021-04-29 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_auto_20210429_0444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_token',
            field=models.CharField(max_length=400, unique=True),
        ),
    ]
